# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Term.create!(term: "Honest")
Term.create!(term: "Active Participant")
Term.create!(term: "Focused")
Term.create!(term: "Passion")
Term.create!(term: "Respectful")
Term.create!(term: "Confident")
Term.create!(term: "Compassionate")
Term.create!(term: "Empowering")
Term.create!(term: "Collaborative")
Term.create!(term: "Supportive")
Term.create!(term: "Reliable")
Term.create!(term: "Communication")
Term.create!(term: "Active Listener")
Term.create!(term: "Cooperative")
Term.create!(term: "Problem-solver")
Term.create!(term: "Creative")
Term.create!(term: "Responsible")
# Term.create!(term: "Adaptable")
Term.create!(term: "Helpful")
Term.create!(term: "Dedicated")
Term.create!(term: "Leader")
Term.create!(term: "Educator")
Term.create!(term: "Inclusive")
Term.create!(term: "Trustworthy")
Term.create!(term: "Empathetic")
Term.create!(term: "Accountable")
Term.create!(term: "Humble")
# Term.create!(term: "Good Manners")
Term.create!(term: "Ethical")
# Term.create!(term: "Sense of Humor")


u1 = User.create!(email: "sally@gmail.com", first_name: "Sally", last_name: "Smith", password: "muller12")
u2 = User.create!(email: "detholm@comcast.net", first_name: "Didrik", last_name: "Etholm", password: "muller12")
u3 = User.create!(email: "Bob@comcast.net", first_name: "Bob", last_name: "Smith", password: "muller12")
u4 = User.create!(email: "Frank@comcast.net", first_name: "Frank", last_name: "O'Connor", password: "muller12")
u5 = User.create!(email: "Jane@comcast.net", first_name: "Jane", last_name: "Haller", password: "muller12")
u6 = User.create!(email: "Sam@comcast.net", first_name: "Sam", last_name: "Lapointe", password: "muller12")
u7 = User.create!(email: "Phil@comcast.net", first_name: "Phil", last_name: "Forester", password: "muller12")
u8 = User.create!(email: "Alex@comcast.net", first_name: "Alex", last_name: "Smith", password: "muller12")
u9 = User.create!(email: "Dave@comcast.net", first_name: "Dave", last_name: "Jones", password: "muller12")
u10 = User.create!(email: "Test@test.com", first_name: "Test", last_name: "User", password: "test123")


t1 = Team.create!(name: "Team One")
t2 = Team.create!(name: "Team Two")

m1 = Membership.create!(user: u1, team: t1)
m2 = Membership.create!(user:u2, team: t1)
m3 = Membership.create!(user:u3, team: t1)
m4 = Membership.create!(user:u4, team: t1)
m5 = Membership.create!(user:u5, team: t1)
m6 = Membership.create!(user:u6, team: t1)
m7 = Membership.create!(user:u7, team: t1)
m8 = Membership.create!(user:u8, team: t1)
m9 = Membership.create!(user:u9, team: t1)
